// Generated by DebugToolSet Font Extractor
// Font: ark-pixel-16px.ttf 16px 8x16
#ifndef ARK_PIXEL_16PX_8X16_FONT_H
#define ARK_PIXEL_16PX_8X16_FONT_H

#include <stdint.h>

typedef struct {
  uint32_t codepoint;
  uint8_t width;
  uint8_t height;
  uint8_t advance;
  int8_t offsetX;
  int8_t offsetY;
  uint32_t dataOffset;
  uint16_t dataSize;
} font_glyph_t;

extern const font_glyph_t ark_pixel_16px_8x16_glyphs[];
extern const uint32_t ark_pixel_16px_8x16_glyph_count;

#endif // ARK_PIXEL_16PX_8X16_FONT_H

