// Generated by DebugToolSet Font Extractor
// Font: msgothic.ttc 16px 8x16
#ifndef MSGOTHIC_8X16_FONT_H
#define MSGOTHIC_8X16_FONT_H

#include <stdint.h>

typedef struct {
  uint32_t codepoint;
  uint8_t width;
  uint8_t height;
  uint8_t advance;
  int8_t offsetX;
  int8_t offsetY;
  uint32_t dataOffset;
  uint16_t dataSize;
} font_glyph_t;

extern const font_glyph_t msgothic_8x16_glyphs[];
extern const uint32_t msgothic_8x16_glyph_count;

#endif // MSGOTHIC_8X16_FONT_H

