// Generated by DebugToolSet Font Extractor
// Font: unifont-13.0.06.ttf 16px 8x16
#ifndef UNIFONT_13_0_06_8X16_FONT_H
#define UNIFONT_13_0_06_8X16_FONT_H

#include <stdint.h>

typedef struct {
  uint32_t codepoint;
  uint8_t width;
  uint8_t height;
  uint8_t advance;
  int8_t offsetX;
  int8_t offsetY;
  uint32_t dataOffset;
  uint16_t dataSize;
} font_glyph_t;

extern const font_glyph_t unifont_13_0_06_8x16_glyphs[];
extern const uint32_t unifont_13_0_06_8x16_glyph_count;

#endif // UNIFONT_13_0_06_8X16_FONT_H

