/// Generates `ui_callbacks.c/h`: one `__weak` empty stub per callback
/// referenced by the project. Users bind their logic by defining the same
/// function (strong symbol) anywhere in their firmware, or by editing the
/// generated stubs (which are never overwritten once they exist).
class CCallbacksCodegen {
  CCallbacksCodegen._();

  static String header(List<String> callbacks) {
    final sb = StringBuffer()
      ..writeln('// Generated by DebugToolSet UI Designer')
      ..writeln('#ifndef UI_CALLBACKS_H')
      ..writeln('#define UI_CALLBACKS_H')
      ..writeln()
      ..writeln('#include <stdint.h>')
      ..writeln()
      ..writeln('#ifdef __cplusplus')
      ..writeln('extern "C" {')
      ..writeln('#endif')
      ..writeln();
    for (final cb in callbacks) {
      sb.writeln('void $cb(int32_t widget_id, int32_t value);');
    }
    sb
      ..writeln()
      ..writeln('#ifdef __cplusplus')
      ..writeln('}')
      ..writeln('#endif')
      ..writeln()
      ..writeln('#endif // UI_CALLBACKS_H')
      ..writeln();
    return sb.toString();
  }

  static String source(List<String> callbacks) {
    final sb = StringBuffer()
      ..writeln('// Generated by DebugToolSet UI Designer')
      ..writeln('// Bind your application logic here: these stubs are weak')
      ..writeln('// symbols, so defining the same function in your own file')
      ..writeln('// overrides them without touching this file.')
      ..writeln('#include "ui_callbacks.h"')
      ..writeln()
      ..writeln('#if defined(__GNUC__)')
      ..writeln('#define UI_WEAK __attribute__((weak))')
      ..writeln('#else')
      ..writeln('#define UI_WEAK')
      ..writeln('#endif')
      ..writeln();
    for (final cb in callbacks) {
      sb
        ..writeln('UI_WEAK void $cb(int32_t widget_id, int32_t value) {')
        ..writeln('  (void)widget_id;')
        ..writeln('  (void)value;')
        ..writeln('}')
        ..writeln();
    }
    return sb.toString();
  }
}
