import '../models/project_serializer.dart';
import '../models/ui_event.dart';
import '../models/ui_project.dart';
import '../models/ui_widget.dart';

class CProjectCodegenResult {
  CProjectCodegenResult({
    required this.source,
    required this.header,
    required this.callbacks,
    required this.warnings,
  });

  final String source;
  final String header;

  /// All callback symbols referenced by the generated tables.
  final List<String> callbacks;
  final List<String> warnings;
}

/// Generates `ui_pages.c/h`: constant page/widget tables plus embedded
/// image data for assets that have converted raw payloads.
class CProjectCodegen {
  CProjectCodegen._();

  static const _typeEnum = {
    'label': 'UI_W_LABEL',
    'image': 'UI_W_IMAGE',
    'button': 'UI_W_BUTTON',
    'panel': 'UI_W_PANEL',
    'line': 'UI_W_LINE',
    'progress': 'UI_W_PROGRESS',
    'slider': 'UI_W_SLIDER',
    'checkbox': 'UI_W_CHECKBOX',
    'switch': 'UI_W_SWITCH',
    'radio': 'UI_W_RADIO',
    'dropdown': 'UI_W_DROPDOWN',
    'textfield': 'UI_W_TEXTFIELD',
    'scrolllist': 'UI_W_LIST',
  };

  static const _eventEnum = {
    UiEventType.onClick: 'UI_EV_CLICK',
    UiEventType.onFocus: 'UI_EV_FOCUS',
    UiEventType.onValueChange: 'UI_EV_VALUE_CHANGE',
    UiEventType.onShow: 'UI_EV_SHOW',
    UiEventType.onHide: 'UI_EV_HIDE',
    UiEventType.onTimer: 'UI_EV_TIMER',
  };

  static const _imageFormatEnum = {
    'rgb565': 0,
    'rgb888': 1,
    'argb8888': 2,
    'gray8': 3,
    'mono1': 4,
  };

  /// [assetReader] returns the converted raw bytes for an asset, or null
  /// when unavailable.
  static Future<CProjectCodegenResult> generate(
    UiProject project, {
    required Future<List<int>?> Function(UiAsset asset) assetReader,
  }) async {
    final warnings = <String>[];
    final callbacks = <String>{};
    final pageSymbols = _pageSymbols(project);

    final sb = StringBuffer()
      ..writeln('// Generated by DebugToolSet UI Designer')
      ..writeln('// Project: ${project.name}')
      ..writeln('#include "ui_pages.h"')
      ..writeln('#include "ui_callbacks.h"')
      ..writeln();

    // Embedded image data.
    for (final asset in project.assets) {
      final bytes = await assetReader(asset);
      if (bytes == null) {
        warnings.add('资源 ${asset.name} 没有可用的转换数据，图片数据为 NULL');
        continue;
      }
      sb.writeln(
          'static const uint8_t ${asset.name}_data[] = {');
      for (var i = 0; i < bytes.length; i += 16) {
        final end = i + 16 > bytes.length ? bytes.length : i + 16;
        sb.writeln('  ${bytes.sublist(i, end).map((b) => '0x${b.toRadixString(16).padLeft(2, '0')}').join(', ')},');
      }
      sb.writeln('};');
      sb.writeln();
    }

    // Per page: event arrays, widget table, page struct.
    for (var pi = 0; pi < project.pages.length; pi++) {
      final page = project.pages[pi];
      final psym = pageSymbols[page.id]!;

      for (final w in page.widgets) {
        final evArray = _eventsArray(
            '_ev_${psym}_${w.name}', w.events, pageSymbols, callbacks, w.name);
        if (evArray != null) sb.writeln(evArray);
      }
      final pageEv =
          _eventsArray('_ev_$psym', page.events, pageSymbols, callbacks, null);
      if (pageEv != null) sb.writeln(pageEv);

      if (page.widgets.isNotEmpty) {
        sb.writeln('static const ui_widget_t _widgets_$psym[] = {');
        for (final w in page.widgets) {
          sb.writeln('  ${_widgetEntry(w, project, psym)},');
        }
        sb.writeln('};');
        sb.writeln();
      }

      sb
        ..writeln('const ui_page_t $psym = {')
        ..writeln('  "${_escape(page.name)}",')
        ..writeln('  0x${_rgb565(page.bgColor).toRadixString(16).padLeft(4, '0')},')
        ..writeln(page.widgets.isEmpty
            ? '  0, 0,'
            : '  _widgets_$psym, ${page.widgets.length},')
        ..writeln(page.events.isEmpty ? '  0, 0,' : '  _ev_$psym, ${page.events.length},')
        ..writeln('};')
        ..writeln();
    }

    final hb = StringBuffer()
      ..writeln('// Generated by DebugToolSet UI Designer')
      ..writeln('#ifndef UI_PAGES_H')
      ..writeln('#define UI_PAGES_H')
      ..writeln()
      ..writeln('#include "ui_runtime.h"')
      ..writeln()
      ..writeln('#define UI_SCREEN_WIDTH ${project.screenWidth}')
      ..writeln('#define UI_SCREEN_HEIGHT ${project.screenHeight}')
      ..writeln();
    for (final sym in pageSymbols.values) {
      hb.writeln('extern const ui_page_t $sym;');
    }
    if (project.pages.isNotEmpty) {
      hb
        ..writeln()
        ..writeln('#define UI_START_PAGE '
            '(&${pageSymbols[project.pages.first.id]})');
    }
    hb
      ..writeln()
      ..writeln('#endif // UI_PAGES_H')
      ..writeln();

    return CProjectCodegenResult(
      source: sb.toString(),
      header: hb.toString(),
      callbacks: callbacks.toList()..sort(),
      warnings: warnings,
    );
  }

  // ------------------------------------------------------------------

  static Map<String, String> _pageSymbols(UiProject project) {
    final result = <String, String>{};
    final used = <String>{};
    for (var i = 0; i < project.pages.length; i++) {
      final page = project.pages[i];
      var sym = sanitizeCIdentifier(page.name) ?? 'page_${i + 1}';
      sym = 'ui_page_$sym';
      var unique = sym;
      var n = 2;
      while (used.contains(unique)) {
        unique = '${sym}_$n';
        n++;
      }
      used.add(unique);
      result[page.id] = unique;
    }
    return result;
  }

  /// Returns the C array definition for [events], or null when empty.
  /// [ownerName] is the widget name (null for page events), used to build
  /// automatic callback names.
  static String? _eventsArray(
    String arrayName,
    List<UiEvent> events,
    Map<String, String> pageSymbols,
    Set<String> callbacks,
    String? ownerName,
  ) {
    if (events.isEmpty) return null;
    final sb = StringBuffer()
      ..writeln('static const ui_event_t $arrayName[] = {');
    for (final e in events) {
      final typeEnum = _eventEnum[e.type]!;
      if (e.action == UiActionType.gotoPage &&
          e.targetPageId != null &&
          pageSymbols.containsKey(e.targetPageId)) {
        sb.writeln(
            '  { $typeEnum, UI_ACT_GOTO_PAGE, 0, '
            '(const void*)&${pageSymbols[e.targetPageId]}, 0 },');
      } else {
        var cb = sanitizeCIdentifier(e.callback);
        if (cb == null) {
          final owner = ownerName ?? 'page';
          cb = 'ui_cb_${owner}_${e.type.name}';
        }
        callbacks.add(cb);
        final timer = e.type == UiEventType.onTimer ? e.timerMs : 0;
        sb.writeln(
            '  { $typeEnum, UI_ACT_CALLBACK, $cb, 0, $timer },');
      }
    }
    sb.writeln('};');
    sb.writeln();
    return sb.toString();
  }

  static String _widgetEntry(UiWidgetModel w, UiProject project, String psym) {
    final p = _propsEntry(w, project);
    final ev =
        w.events.isEmpty ? '0, 0' : '_ev_${psym}_${w.name}, ${w.events.length}';
    return '{ ${w.x.round()}, ${w.y.round()}, ${w.width.round()}, '
        '${w.height.round()}, ${_typeEnum[w.type] ?? 'UI_W_LABEL'}, '
        '"${_escape(w.name)}", $p, $ev }';
  }

  static String _propsEntry(UiWidgetModel w, UiProject project) {
    String text = '0', text2 = '0', image = '0';
    var value = 0, min = 0, max = 0;
    var color = 0xFFFF, color2 = 0, borderColor = 0;
    var imageW = 0, imageH = 0;
    var fontSize = 14, align = 0, radius = 0, borderWidth = 0;
    var flags = 0, scaleMode = 0, imageFormat = 0;

    final props = w.props;
    int colorProp(String key, [int fallback = 0]) =>
        _rgb565(props[key] as int? ?? fallback);

    switch (w.type) {
      case 'label':
        text = _cstr(props['text'] as String? ?? '');
        fontSize = (props['fontSize'] as num?)?.toInt() ?? 14;
        color = colorProp('color', 0xFFFFFFFF);
        align = _alignEnum(props['align'] as String? ?? 'left');
        if (props['bold'] as bool? ?? false) flags |= 0x01;
      case 'image':
        final assetId = props['asset'] as String?;
        final asset = assetId == null ? null : project.assetById(assetId);
        if (asset != null) {
          image = '${asset.name}_data';
          imageW = asset.width;
          imageH = asset.height;
          imageFormat = _imageFormatEnum[asset.format] ?? 0;
        }
        scaleMode = const {'fit': 0, 'fill': 1, 'stretch': 2}[
                props['scaleMode'] as String? ?? 'fit'] ??
            0;
      case 'button':
        text = _cstr(props['text'] as String? ?? '');
        fontSize = (props['fontSize'] as num?)?.toInt() ?? 14;
        color = colorProp('bgColor', 0xFF1E88E5);
        color2 = colorProp('pressedColor', 0xFF0D47A1);
        borderColor = colorProp('textColor', 0xFFFFFFFF);
        radius = (props['radius'] as num?)?.toInt() ?? 6;
      case 'panel':
        color = colorProp('bgColor', 0xFF2E2E2E);
        radius = (props['radius'] as num?)?.toInt() ?? 0;
        borderColor = colorProp('borderColor');
        borderWidth = (props['borderWidth'] as num?)?.toInt() ?? 0;
      case 'line':
        color = colorProp('color', 0xFF9E9E9E);
        radius = (props['thickness'] as num?)?.toInt() ?? 1;
      case 'progress':
        value = (props['value'] as num?)?.toInt() ?? 0;
        max = (props['max'] as num?)?.toInt() ?? 100;
        color = colorProp('color', 0xFF4CAF50);
        color2 = colorProp('bgColor', 0xFF424242);
        radius = (props['radius'] as num?)?.toInt() ?? 4;
      case 'slider':
        value = (props['value'] as num?)?.toInt() ?? 0;
        min = (props['min'] as num?)?.toInt() ?? 0;
        max = (props['max'] as num?)?.toInt() ?? 100;
        color = colorProp('color', 0xFF1E88E5);
        color2 = colorProp('trackColor', 0xFF616161);
      case 'checkbox':
        text = _cstr(props['text'] as String? ?? '');
        fontSize = (props['fontSize'] as num?)?.toInt() ?? 14;
        color = colorProp('color', 0xFF1E88E5);
        if (props['checked'] as bool? ?? false) flags |= 0x02;
      case 'switch':
        color = colorProp('color', 0xFF1E88E5);
        color2 = 0x4208; // grey track when off
        if (props['on'] as bool? ?? false) flags |= 0x02;
      case 'radio':
        text = _cstr(props['text'] as String? ?? '');
        text2 = _cstr(props['group'] as String? ?? '');
        fontSize = (props['fontSize'] as num?)?.toInt() ?? 14;
        color = colorProp('color', 0xFF1E88E5);
        if (props['checked'] as bool? ?? false) flags |= 0x02;
      case 'dropdown':
        final options = props['options'] as String? ?? '';
        final idx = (props['selectedIndex'] as num?)?.toInt() ?? 0;
        final list =
            options.split(',').map((s) => s.trim()).toList(growable: false);
        text = _cstr(idx >= 0 && idx < list.length ? list[idx] : '');
        text2 = _cstr(options);
        value = idx;
        fontSize = (props['fontSize'] as num?)?.toInt() ?? 14;
        color = colorProp('textColor', 0xFFFFFFFF);
        color2 = colorProp('bgColor', 0xFF424242);
      case 'textfield':
        text = _cstr(props['text'] as String? ?? '');
        text2 = _cstr(props['hint'] as String? ?? '');
        fontSize = (props['fontSize'] as num?)?.toInt() ?? 14;
        color = colorProp('textColor', 0xFFFFFFFF);
        color2 = colorProp('bgColor', 0xFF2E2E2E);
        radius = (props['radius'] as num?)?.toInt() ?? 4;
      case 'scrolllist':
        text2 = _cstr(props['items'] as String? ?? '');
        value = (props['selectedIndex'] as num?)?.toInt() ?? 0;
        fontSize = (props['fontSize'] as num?)?.toInt() ?? 16;
        color = colorProp('textColor', 0xFFFFFFFF);
        color2 = colorProp('selectedColor', 0xFF1E88E5);
        align = (props['orientation'] as String? ?? 'vertical') == 'vertical'
            ? 0
            : 1;
        radius = (props['itemExtent'] as num?)?.toInt() ?? 36;
        borderWidth = (props['spacing'] as num?)?.toInt() ?? 4;
    }

    return '{ $text, $text2, $image, $value, $min, $max, '
        '${_hex16(color)}, ${_hex16(color2)}, ${_hex16(borderColor)}, '
        '$imageW, $imageH, $fontSize, $align, $radius, $borderWidth, '
        '$flags, $scaleMode, $imageFormat }';
  }

  static int _alignEnum(String a) =>
      const {'left': 0, 'center': 1, 'right': 2}[a] ?? 0;

  static String _hex16(int v) =>
      '0x${v.toRadixString(16).padLeft(4, '0')}';

  static int _rgb565(int argb) {
    final r = (argb >> 16) & 0xFF;
    final g = (argb >> 8) & 0xFF;
    final b = argb & 0xFF;
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
  }

  static String _escape(String s) => s
      .replaceAll('\\', '\\\\')
      .replaceAll('"', '\\"')
      .replaceAll('\n', '\\n');

  static String _cstr(String s) => '"${_escape(s)}"';
}
