import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';
import 'package:path/path.dart' as p;
import 'package:provider/provider.dart';

import '../../../providers/ui_designer_state.dart';
import '../models/project_serializer.dart';
import 'pixel_formats.dart';

/// Image conversion tool: PNG/JPG/BMP → raw bytes (RGB565/RGB888/ARGB8888/
/// 灰度/1bpp), exported as C array or .bin, or stored as a project asset.
Future<void> showImageConverterDialog(BuildContext context) {
  return showDialog<void>(
    context: context,
    builder: (_) => const ImageConverterDialog(),
  );
}

class ImageConverterDialog extends StatefulWidget {
  const ImageConverterDialog({super.key});

  @override
  State<ImageConverterDialog> createState() => _ImageConverterDialogState();
}

class _ImageConverterDialogState extends State<ImageConverterDialog> {
  String? _filePath;
  ui.Image? _image;
  Uint8ListWrapper? _rgba;
  PixelFormat _format = PixelFormat.rgb565;
  bool _columnMajor = false;
  String? _message;
  bool _busy = false;

  @override
  void dispose() {
    _image?.dispose();
    super.dispose();
  }

  Future<void> _pickFile() async {
    final file = await openFile(acceptedTypeGroups: const [
      XTypeGroup(label: '图片', extensions: ['png', 'jpg', 'jpeg', 'bmp'])
    ]);
    if (file == null) return;
    setState(() {
      _busy = true;
      _message = null;
    });
    try {
      final bytes = await file.readAsBytes();
      final codec = await ui.instantiateImageCodec(bytes);
      final frame = await codec.getNextFrame();
      final data =
          await frame.image.toByteData(format: ui.ImageByteFormat.rawRgba);
      if (data == null) throw StateError('无法读取像素数据');
      _image?.dispose();
      setState(() {
        _filePath = file.path;
        _image = frame.image;
        _rgba = Uint8ListWrapper(data.buffer.asUint8List());
      });
    } catch (e) {
      setState(() => _message = '图片解码失败: $e');
    } finally {
      setState(() => _busy = false);
    }
  }

  Uint8List? _convert() {
    final rgba = _rgba;
    final image = _image;
    if (rgba == null || image == null) return null;
    return rgbaToRaw(rgba.bytes, image.width, image.height, _format,
        columnMajor: _columnMajor);
  }

  String get _baseName =>
      sanitizeCIdentifier(
          p.basenameWithoutExtension(_filePath ?? 'image')) ??
      'image';

  Future<void> _exportCArray() async {
    final raw = _convert();
    if (raw == null) return;
    final location = await getSaveLocation(
      acceptedTypeGroups: const [
        XTypeGroup(label: 'C 源文件', extensions: ['c'])
      ],
      suggestedName: '${_baseName}_image.c',
    );
    if (location == null) return;
    final sb = StringBuffer()
      ..writeln('// Generated by DebugToolSet Image Converter')
      ..writeln('// Source: ${p.basename(_filePath!)} '
          '${_image!.width}x${_image!.height} '
          '${_format.label}${_columnMajor ? ' 列扫描' : ' 行扫描'}')
      ..writeln('#include <stdint.h>')
      ..writeln()
      ..writeln(
          'const uint8_t ${_baseName}_data[] = {')
      ..write(bytesToCArrayBody(raw))
      ..writeln('};')
      ..writeln(
          'const uint32_t ${_baseName}_data_size = ${raw.length};')
      ..writeln(
          'const uint16_t ${_baseName}_width = ${_image!.width};')
      ..writeln(
          'const uint16_t ${_baseName}_height = ${_image!.height};');
    await File(location.path).writeAsString(sb.toString());
    setState(() => _message = '已导出 C 数组: ${location.path}');
  }

  Future<void> _exportBin() async {
    final raw = _convert();
    if (raw == null) return;
    final location = await getSaveLocation(
      acceptedTypeGroups: const [
        XTypeGroup(label: '二进制', extensions: ['bin'])
      ],
      suggestedName: '$_baseName.bin',
    );
    if (location == null) return;
    await File(location.path).writeAsBytes(raw);
    setState(() => _message = '已导出 bin: ${location.path} (${raw.length} 字节)');
  }

  Future<void> _storeAsAsset() async {
    final raw = _convert();
    if (raw == null || _filePath == null) return;
    final state = context.read<UiDesignerState>();
    // Write the converted payload next to the source image.
    final binPath = p.join(
        p.dirname(_filePath!), '${_baseName}_${_format.name}.bin');
    await File(binPath).writeAsBytes(raw);
    final asset = state.importAsset(_filePath!, name: _baseName);
    asset
      ..binFile = binPath
      ..format = _format.name
      ..width = _image!.width
      ..height = _image!.height;
    setState(() => _message = '已存入工程资源: ${asset.name}');
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      backgroundColor: const Color(0xFF2E2E2E),
      title: const Text('图片转换工具', style: TextStyle(fontSize: 14)),
      content: SizedBox(
        width: 520,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                ElevatedButton.icon(
                  onPressed: _busy ? null : _pickFile,
                  icon: const Icon(Icons.folder_open, size: 16),
                  label: const Text('选择图片',
                      style: TextStyle(fontSize: 12)),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: Text(
                    _filePath == null
                        ? '未选择'
                        : '${p.basename(_filePath!)} '
                            '(${_image?.width}x${_image?.height})',
                    overflow: TextOverflow.ellipsis,
                    style:
                        const TextStyle(fontSize: 12, color: Colors.grey),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 10),
            Row(
              children: [
                const Text('像素格式',
                    style: TextStyle(fontSize: 12, color: Colors.grey)),
                const SizedBox(width: 8),
                DropdownButton<PixelFormat>(
                  value: _format,
                  isDense: true,
                  style: const TextStyle(fontSize: 12),
                  items: [
                    for (final f in PixelFormat.values)
                      DropdownMenuItem(value: f, child: Text(f.label)),
                  ],
                  onChanged: (v) => setState(() => _format = v!),
                ),
                const SizedBox(width: 16),
                const Text('扫描方向',
                    style: TextStyle(fontSize: 12, color: Colors.grey)),
                const SizedBox(width: 8),
                DropdownButton<bool>(
                  value: _columnMajor,
                  isDense: true,
                  style: const TextStyle(fontSize: 12),
                  items: const [
                    DropdownMenuItem(value: false, child: Text('行扫描')),
                    DropdownMenuItem(value: true, child: Text('列扫描')),
                  ],
                  onChanged: (v) =>
                      setState(() => _columnMajor = v ?? false),
                ),
              ],
            ),
            const SizedBox(height: 10),
            Container(
              height: 180,
              width: double.infinity,
              decoration: BoxDecoration(
                color: const Color(0xFF1B1B1B),
                border: Border.all(color: Colors.grey.shade800),
              ),
              child: _busy
                  ? const Center(child: CircularProgressIndicator())
                  : _filePath == null
                      ? const Center(
                          child: Text('预览',
                              style: TextStyle(
                                  fontSize: 12, color: Colors.grey)))
                      : Image.file(File(_filePath!), fit: BoxFit.contain),
            ),
            const SizedBox(height: 10),
            Row(
              children: [
                _actionButton('导出 C 数组', _exportCArray),
                const SizedBox(width: 8),
                _actionButton('导出 bin', _exportBin),
                const SizedBox(width: 8),
                _actionButton('存入工程资源', _storeAsAsset),
              ],
            ),
            if (_message != null) ...[
              const SizedBox(height: 8),
              Text(_message!,
                  style: const TextStyle(
                      fontSize: 11, color: Colors.cyanAccent)),
            ],
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('关闭'),
        ),
      ],
    );
  }

  Widget _actionButton(String label, VoidCallback onPressed) {
    final enabled = _image != null && !_busy;
    return ElevatedButton(
      onPressed: enabled ? onPressed : null,
      style: ElevatedButton.styleFrom(
        backgroundColor: const Color(0xFF0A4A5A),
        foregroundColor: Colors.cyanAccent,
        minimumSize: const Size(0, 30),
      ),
      child: Text(label, style: const TextStyle(fontSize: 12)),
    );
  }
}

/// Tiny wrapper to keep the decoded pixel buffer with a stable type.
class Uint8ListWrapper {
  Uint8ListWrapper(this.bytes);

  final Uint8List bytes;
}
