; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "DebugToolset"
#define MyAppVersion "0.0.3"
#define MyAppPublisher "FZDL.CG"
#define MyAppURL "https://github.com/mustaches/DebugToolset"
#define MyAppExeName "debug_tool_set.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{F97CFF64-4DF0-4BB8-935F-D0CD39526877}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=G:\DebugToolSet\Windows_setup\Output
OutputBaseFilename=DebugToolset_setup
SetupIconFile=G:\DebugToolSet\windows\runner\resources\app_icon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "G:\DebugToolSet\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "G:\DebugToolSet\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "G:\DebugToolSet\bussetup\*"; DestDir: "{app}\bussetup"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "G:\DebugToolSet\DeviceProtocol\*"; DestDir: "{app}\DeviceProtocol"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "G:\DebugToolSet\docs\*"; DestDir: "{app}\docs"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "G:\DebugToolSet\waveform\*"; DestDir: "{app}\waveform"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "G:\DebugToolSet\tools\*"; DestDir: "{app}\tools"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "G:\DebugToolSet\IspFlow\*"; DestDir: "{app}\IspFlow"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "G:\DebugToolSet\Font\*"; DestDir: "{app}\Font"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "G:\DebugToolSet\UI_Project\*"; DestDir: "{app}\UI_Project"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

