// Generated by DebugToolSet Font Extractor
// Font: cour.ttf 30px 16x32
#ifndef COURIER_NEW_16X32_FONT_H
#define COURIER_NEW_16X32_FONT_H

#include <stdint.h>

typedef struct {
  uint32_t codepoint;
  uint8_t width;
  uint8_t height;
  uint8_t advance;
  int8_t offsetX;
  int8_t offsetY;
  uint32_t dataOffset;
  uint16_t dataSize;
} font_glyph_t;

extern const font_glyph_t Courier_New_16x32_glyphs[];
extern const uint32_t Courier_New_16x32_glyph_count;

#endif // COURIER_NEW_16X32_FONT_H

