// Generated by DebugToolSet UI Designer
// Project: gpu_effects_demo
#include "ui_pages.h"
#include "ui_callbacks.h"

static const ui_event_t _ev_ui_page_page_1_main_menu[] = {
  { UI_EV_VALUE_CHANGE, UI_ACT_CALLBACK, on_menu_highlight, 0, 0, 0 },
  { UI_EV_CLICK, UI_ACT_GOTO_PAGE, 0, (const void*)&ui_page_page_2, 0, 1 },
};


static const ui_event_t _ev_ui_page_page_1_btn_fx[] = {
  { UI_EV_CLICK, UI_ACT_GOTO_PAGE, 0, (const void*)&ui_page_page_2, 0, 5 },
};


static const ui_event_t _ev_ui_page_page_1_btn_about[] = {
  { UI_EV_CLICK, UI_ACT_GOTO_PAGE, 0, (const void*)&ui_page_page_3, 0, 3 },
};


static const ui_widget_t _widgets_ui_page_page_1[] = {
  { 16, 10, 240, 26, UI_W_LABEL, "title", { "GPU 特效演示", 0, 0, 0, 0, 0, 0xffff, 0x0000, 0x0000, 0, 0, 20, 0, 0, 0, 1, 0, 0 }, 0, 0, 0, 100, 90 },
  { 410, 8, 48, 48, UI_W_IMAGE, "badge", { 0, 0, 0, 0, 0, 0, 0xffff, 0x0000, 0x0000, 0, 0, 14, 0, 0, 0, 0, 0, 0 }, 0, 0, 30, 120, 85 },
  { 24, 52, 200, 180, UI_W_MENU, "main_menu", { 0, "相机预览,参数设置,特效切换,系统信息,关于", 0, 0, 0, 0, 0xffff, 0x034b, 0x0000, 0, 0, 15, 0, 34, 0, 4, 0, 0 }, _ev_ui_page_page_1_main_menu, 2, 0, 100, 100 },
  { 248, 60, 208, 34, UI_W_PROGRESS, "progress", { "固件下载", 0, 0, 65, 0, 100, 0x044f, 0x4208, 0x4db5, 0, 0, 12, 0, 4, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 248, 116, 96, 34, UI_W_BUTTON, "btn_fx", { "特效页", 0, 0, 0, 0, 0, 0x034b, 0x0a34, 0xffff, 0, 0, 14, 0, 8, 0, 0, 0, 0 }, _ev_ui_page_page_1_btn_fx, 1, 0, 100, 100 },
  { 356, 116, 96, 34, UI_W_BUTTON, "btn_about", { "关于", 0, 0, 0, 0, 0, 0x3229, 0x0a34, 0xffff, 0, 0, 14, 0, 8, 0, 0, 0, 0 }, _ev_ui_page_page_1_btn_about, 1, 0, 100, 100 },
  { 24, 240, 432, 16, UI_W_LABEL, "hint", { "方向键移动焦点 · 上下键操作菜单 · OK 进入 · 注意转场与动效", 0, 0, 0, 0, 0, 0x5bf3, 0x0000, 0x0000, 0, 0, 10, 0, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
};

const ui_page_t ui_page_page_1 = {
  "主界面",
  0x0842,
  _widgets_ui_page_page_1, 7,
  0, 0,
  0, 0, 0, 0, 0, 0,
};

static const ui_event_t _ev_ui_page_page_2_exposure[] = {
  { UI_EV_VALUE_CHANGE, UI_ACT_CALLBACK, on_exposure, 0, 0, 0 },
};


static const ui_event_t _ev_ui_page_page_2_btn_back[] = {
  { UI_EV_CLICK, UI_ACT_GOTO_PAGE, 0, (const void*)&ui_page_page_1, 0, 2 },
};


static const ui_widget_t _widgets_ui_page_page_2[] = {
  { 16, 10, 240, 26, UI_W_LABEL, "settings_title", { "参数设置", 0, 0, 0, 0, 0, 0xffff, 0x0000, 0x0000, 0, 0, 20, 0, 0, 0, 1, 0, 0 }, 0, 0, 0, 100, 100 },
  { 32, 56, 240, 28, UI_W_VALUE_ITEM, "exposure", { "曝光补偿", 0, 0, 50, 0, 100, 0xffff, 0x4e1e, 0x0000, 0, 0, 14, 0, 5, 0, 0, 0, 0 }, _ev_ui_page_page_2_exposure, 1, 0, 100, 100 },
  { 32, 92, 240, 28, UI_W_VALUE_ITEM, "iso", { "ISO", 0, 0, 200, 100, 6400, 0xffff, 0x4e1e, 0x0000, 0, 0, 14, 0, 100, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 32, 128, 240, 28, UI_W_OPTION_ITEM, "white_balance", { "白平衡", "自动,日光,阴天,白炽灯,荧光灯", 0, 0, 0, 0, 0xffff, 0x4e1e, 0x0000, 0, 0, 14, 0, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 32, 164, 240, 28, UI_W_OPTION_ITEM, "resolution", { "分辨率", "4K,1080P,720P", 0, 1, 0, 0, 0xffff, 0x4e1e, 0x0000, 0, 0, 14, 0, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 320, 220, 120, 36, UI_W_BUTTON, "btn_back", { "返回", 0, 0, 0, 0, 0, 0x3229, 0x0a34, 0xffff, 0, 0, 14, 0, 8, 0, 0, 0, 0 }, _ev_ui_page_page_2_btn_back, 1, 0, 100, 100 },
  { 32, 232, 260, 16, UI_W_LABEL, "settings_hint", { "左右键调值/切换选项 · OK 确认", 0, 0, 0, 0, 0, 0x5bf3, 0x0000, 0x0000, 0, 0, 10, 0, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
};

const ui_page_t ui_page_page_2 = {
  "参数设置",
  0x10c4,
  _widgets_ui_page_page_2, 7,
  0, 0,
  0, 0, 0, 0, 0, 0,
};

static const ui_event_t _ev_ui_page_page_3_btn_aback[] = {
  { UI_EV_CLICK, UI_ACT_GOTO_PAGE, 0, (const void*)&ui_page_page_1, 0, 4 },
};


static const ui_widget_t _widgets_ui_page_page_3[] = {
  { 16, 10, 240, 26, UI_W_LABEL, "about_title", { "关于(视频背景 OSD)", 0, 0, 0, 0, 0, 0xffff, 0x0000, 0x0000, 0, 0, 20, 0, 0, 0, 1, 0, 0 }, 0, 0, 0, 100, 100 },
  { 16, 48, 300, 20, UI_W_LABEL, "about_ver", { "GPU Effects Demo v1.0 · Mali MP2", 0, 0, 0, 0, 0, 0x9e1c, 0x0000, 0x0000, 0, 0, 13, 0, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 16, 80, 240, 80, UI_W_PANEL, "about_panel", { 0, 0, 0, 0, 0, 0, 0x0000, 0x0000, 0x0000, 0, 0, 14, 0, 8, 0, 0, 0, 0 }, 0, 0, 0, 100, 90 },
  { 28, 92, 220, 56, UI_W_LABEL, "about_note", { "视频背景下控件直接叠加在实时画面上", 0, 0, 0, 0, 0, 0xffff, 0x0000, 0x0000, 0, 0, 12, 0, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 340, 220, 120, 36, UI_W_BUTTON, "btn_aback", { "返回", 0, 0, 0, 0, 0, 0x1c5c, 0x0a34, 0xffff, 0, 0, 14, 0, 8, 0, 0, 0, 0 }, _ev_ui_page_page_3_btn_aback, 1, 0, 100, 100 },
};

const ui_page_t ui_page_page_3 = {
  "关于",
  0x0000,
  _widgets_ui_page_page_3, 5,
  0, 0,
  2, 0, 0, 0, 0, 0,
};

