// Generated by DebugToolSet UI Designer
#ifndef UI_CALLBACKS_H
#define UI_CALLBACKS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

void on_ok_click(int32_t widget_id, int32_t value);
void tick_update(int32_t widget_id, int32_t value);
void ui_cb_slider_vol_onValueChange(int32_t widget_id, int32_t value);

#ifdef __cplusplus
}
#endif

#endif // UI_CALLBACKS_H

