// Generated by DebugToolSet UI Designer
// Project: demo
#include "ui_pages.h"
#include "ui_callbacks.h"

static const ui_event_t _ev_ui_page_main_btn_ok[] = {
  { UI_EV_CLICK, UI_ACT_CALLBACK, on_ok_click, 0, 0 },
  { UI_EV_FOCUS, UI_ACT_GOTO_PAGE, 0, (const void*)&ui_page_settings, 0 },
};


static const ui_event_t _ev_ui_page_main_slider_vol[] = {
  { UI_EV_VALUE_CHANGE, UI_ACT_CALLBACK, ui_cb_slider_vol_onValueChange, 0, 0 },
};


static const ui_event_t _ev_ui_page_main[] = {
  { UI_EV_TIMER, UI_ACT_CALLBACK, tick_update, 0, 500 },
};


static const ui_widget_t _widgets_ui_page_main[] = {
  { 10, 8, 200, 30, UI_W_LABEL, "title_1", { "Hello", 0, 0, 0, 0, 0, 0xffff, 0x0000, 0x0000, 0, 0, 14, 0, 0, 0, 0, 0, 0 }, 0, 0 },
  { 20, 60, 100, 40, UI_W_BUTTON, "btn_ok", { "OK", 0, 0, 0, 0, 0, 0x1c5c, 0x0a34, 0xffff, 0, 0, 14, 0, 6, 0, 0, 0, 0 }, _ev_ui_page_main_btn_ok, 2 },
  { 20, 120, 180, 30, UI_W_SLIDER, "slider_vol", { 0, 0, 0, 50, 0, 100, 0x1c5c, 0x630c, 0x0000, 0, 0, 14, 0, 0, 0, 0, 0, 0 }, _ev_ui_page_main_slider_vol, 1 },
};

const ui_page_t ui_page_main = {
  "main",
  0x1082,
  _widgets_ui_page_main, 3,
  _ev_ui_page_main, 1,
};

const ui_page_t ui_page_settings = {
  "settings",
  0x2104,
  0, 0,
  0, 0,
};

