// Generated by DebugToolSet UI Designer
#ifndef UI_CALLBACKS_H
#define UI_CALLBACKS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

void on_emulator_changed(int32_t widget_id, int32_t value);
void on_game_changed(int32_t widget_id, int32_t value);
void on_game_start(int32_t widget_id, int32_t value);

#ifdef __cplusplus
}
#endif

#endif // UI_CALLBACKS_H

