// Generated by DebugToolSet UI Designer
// Bind your application logic here: these stubs are weak
// symbols, so defining the same function in your own file
// overrides them without touching this file.
#include "ui_callbacks.h"

#if defined(__GNUC__)
#define UI_WEAK __attribute__((weak))
#else
#define UI_WEAK
#endif

UI_WEAK void on_emulator_changed(int32_t widget_id, int32_t value) {
  (void)widget_id;
  (void)value;
}

UI_WEAK void on_game_changed(int32_t widget_id, int32_t value) {
  (void)widget_id;
  (void)value;
}

UI_WEAK void on_game_start(int32_t widget_id, int32_t value) {
  (void)widget_id;
  (void)value;
}

