// Generated by DebugToolSet UI Designer
// Project: psp_emulator
#include "ui_pages.h"
#include "ui_callbacks.h"

static const ui_event_t _ev_ui_page_page_1_emu_list[] = {
  { UI_EV_VALUE_CHANGE, UI_ACT_CALLBACK, on_emulator_changed, 0, 0, 0 },
};


static const ui_event_t _ev_ui_page_page_1_game_list[] = {
  { UI_EV_VALUE_CHANGE, UI_ACT_CALLBACK, on_game_changed, 0, 0, 0 },
};


static const ui_event_t _ev_ui_page_page_1_btn_start[] = {
  { UI_EV_CLICK, UI_ACT_CALLBACK, on_game_start, 0, 0, 0 },
};


static const ui_event_t _ev_ui_page_page_1_btn_detail[] = {
  { UI_EV_CLICK, UI_ACT_GOTO_PAGE, 0, (const void*)&ui_page_page_2, 0, 0 },
};


static const ui_widget_t _widgets_ui_page_page_1[] = {
  { 0, 0, 480, 34, UI_W_PANEL, "top_bar", { 0, 0, 0, 0, 0, 0, 0x0149, 0x0000, 0x0000, 0, 0, 14, 0, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 14, 5, 220, 24, UI_W_LABEL, "title", { "PSP 模拟器", 0, 0, 0, 0, 0, 0xffff, 0x0000, 0x0000, 0, 0, 18, 0, 0, 0, 1, 0, 0 }, 0, 0, 0, 100, 100 },
  { 396, 8, 70, 20, UI_W_LABEL, "clock", { "14:30", 0, 0, 0, 0, 0, 0x9e1c, 0x0000, 0x0000, 0, 0, 12, 2, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 0, 34, 480, 2, UI_W_LINE, "top_line", { 0, 0, 0, 0, 0, 0, 0x09cc, 0x0000, 0x0000, 0, 0, 14, 0, 2, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 24, 44, 120, 18, UI_W_LABEL, "emu_header", { "模拟器", 0, 0, 0, 0, 0, 0x7d59, 0x0000, 0x0000, 0, 0, 12, 0, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 24, 66, 150, 200, UI_W_LIST, "emu_list", { 0, "PSP,PS1,GBA,GBC,NDS,FC,SFC,MD,街机,N64", 0, 0, 0, 0, 0xffff, 0x1c5c, 0x0000, 0, 0, 16, 0, 36, 6, 0, 0, 0 }, _ev_ui_page_page_1_emu_list, 1, 0, 100, 100 },
  { 194, 44, 120, 18, UI_W_LABEL, "game_header", { "游戏", 0, 0, 0, 0, 0, 0x7d59, 0x0000, 0x0000, 0, 0, 12, 0, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 194, 96, 262, 90, UI_W_LIST, "game_list", { 0, "怪物猎人,战神,最终幻想,山脊赛车,合金装备,啪嗒砰,实况足球,寂静岭", 0, 0, 0, 0, 0xffff, 0x1c5c, 0x0000, 0, 0, 14, 1, 80, 8, 0, 0, 0 }, _ev_ui_page_page_1_game_list, 1, 0, 100, 100 },
  { 194, 196, 262, 16, UI_W_LABEL, "hint", { "上下滑动选模拟器，左右滑动选游戏", 0, 0, 0, 0, 0, 0x5bf3, 0x0000, 0x0000, 0, 0, 10, 0, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 330, 226, 120, 38, UI_W_BUTTON, "btn_start", { "开始游戏", 0, 0, 0, 0, 0, 0x1c5c, 0x0a34, 0xffff, 0, 0, 14, 0, 8, 0, 0, 0, 0 }, _ev_ui_page_page_1_btn_start, 1, 0, 100, 100 },
  { 194, 226, 120, 38, UI_W_BUTTON, "btn_detail", { "游戏详情", 0, 0, 0, 0, 0, 0x3229, 0x2187, 0xffff, 0, 0, 14, 0, 8, 0, 0, 0, 0 }, _ev_ui_page_page_1_btn_detail, 1, 0, 100, 100 },
  { 14, 258, 300, 16, UI_W_LABEL, "footer", { "DebugToolSet UI Designer", 0, 0, 0, 0, 0, 0x3aef, 0x0000, 0x0000, 0, 0, 10, 0, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
};

const ui_page_t ui_page_page_1 = {
  "主界面",
  0x00a5,
  _widgets_ui_page_page_1, 12,
  0, 0,
  0, 0, 0, 0, 0, 0,
};

static const ui_event_t _ev_ui_page_page_2_btn_back[] = {
  { UI_EV_CLICK, UI_ACT_GOTO_PAGE, 0, (const void*)&ui_page_page_1, 0, 0 },
};


static const ui_event_t _ev_ui_page_page_2_btn_launch[] = {
  { UI_EV_CLICK, UI_ACT_CALLBACK, on_game_start, 0, 0, 0 },
};


static const ui_widget_t _widgets_ui_page_page_2[] = {
  { 40, 40, 400, 180, UI_W_PANEL, "detail_card", { 0, 0, 0, 0, 0, 0, 0x1947, 0x0000, 0x2a4d, 0, 0, 14, 0, 12, 1, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 60, 56, 200, 28, UI_W_LABEL, "detail_title", { "游戏详情", 0, 0, 0, 0, 0, 0xffff, 0x0000, 0x0000, 0, 0, 20, 0, 0, 0, 1, 0, 0 }, 0, 0, 0, 100, 100 },
  { 60, 96, 240, 20, UI_W_LABEL, "detail_name", { "名称：怪物猎人 P3", 0, 0, 0, 0, 0, 0xffff, 0x0000, 0x0000, 0, 0, 14, 0, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 60, 122, 240, 20, UI_W_LABEL, "detail_platform", { "平台：PSP", 0, 0, 0, 0, 0, 0xffff, 0x0000, 0x0000, 0, 0, 14, 0, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 60, 148, 240, 20, UI_W_LABEL, "detail_size", { "大小：1.2 GB", 0, 0, 0, 0, 0, 0xffff, 0x0000, 0x0000, 0, 0, 14, 0, 0, 0, 0, 0, 0 }, 0, 0, 0, 100, 100 },
  { 60, 230, 100, 36, UI_W_BUTTON, "btn_back", { "返回", 0, 0, 0, 0, 0, 0x3229, 0x2187, 0xffff, 0, 0, 14, 0, 6, 0, 0, 0, 0 }, _ev_ui_page_page_2_btn_back, 1, 0, 100, 100 },
  { 320, 230, 100, 36, UI_W_BUTTON, "btn_launch", { "启动", 0, 0, 0, 0, 0, 0x1c5c, 0x0a34, 0xffff, 0, 0, 14, 0, 6, 0, 0, 0, 0 }, _ev_ui_page_page_2_btn_launch, 1, 0, 100, 100 },
};

const ui_page_t ui_page_page_2 = {
  "游戏详情",
  0x10c4,
  _widgets_ui_page_page_2, 7,
  0, 0,
  0, 0, 0, 0, 0, 0,
};

