// Generated by DebugToolSet UI Designer
#ifndef UI_PAGES_H
#define UI_PAGES_H

#include "ui_runtime.h"

#define UI_SCREEN_WIDTH 480
#define UI_SCREEN_HEIGHT 282

extern const ui_page_t ui_page_page_1;
extern const ui_page_t ui_page_page_2;

#define UI_START_PAGE (&ui_page_page_1)

#endif // UI_PAGES_H

