import 'packed_glyph.dart';

/// Generates a C source/header pair containing the extracted font data.
///
/// Layout:
/// - a flat `uint8_t` array with all packed bitmaps concatenated
/// - a glyph descriptor table indexing into that array
class CArrayExporter {
  CArrayExporter._();

  /// Renders [glyphs] as a `.c` source file and matching `.h` header.
  /// Returns `(source, header)`.
  static ({String source, String header}) export({
    required String symbolName,
    required String fontLabel,
    required int cellWidth,
    required int cellHeight,
    required int bitsPerPixel,
    required List<PackedGlyph> glyphs,
  }) {
    final sb = StringBuffer();
    sb.writeln('// Generated by DebugToolSet Font Extractor');
    sb.writeln('// Font: $fontLabel');
    sb.writeln('// Cell: ${cellWidth}x$cellHeight, BPP: $bitsPerPixel, '
        'Glyphs: ${glyphs.length}');
    sb.writeln();
    sb.writeln('#include "${symbolName}_font.h"');
    sb.writeln();
    sb.writeln('static const uint8_t ${symbolName}_data[] = {');

    final offsets = <int>[];
    int offset = 0;
    final allBytes = <int>[];
    for (final g in glyphs) {
      offsets.add(offset);
      allBytes.addAll(g.data);
      offset += g.data.length;
    }
    _writeByteArray(sb, allBytes);
    sb.writeln('};');
    sb.writeln();

    sb.writeln('const font_glyph_t ${symbolName}_glyphs[] = {');
    for (int i = 0; i < glyphs.length; i++) {
      final g = glyphs[i];
      sb.writeln(
        '  { 0x${g.codePoint.toRadixString(16).toUpperCase().padLeft(4, '0')}, '
        '${g.width}, ${g.height}, ${g.advance}, ${g.offsetX}, ${g.offsetY}, '
        '${offsets[i]}, ${g.data.length} },',
      );
    }
    sb.writeln('};');
    sb.writeln();
    sb.writeln('const uint32_t ${symbolName}_glyph_count = ${glyphs.length};');
    sb.writeln();

    final hb = StringBuffer();
    hb.writeln('// Generated by DebugToolSet Font Extractor');
    hb.writeln('// Font: $fontLabel');
    hb.writeln('#ifndef ${symbolName.toUpperCase()}_FONT_H');
    hb.writeln('#define ${symbolName.toUpperCase()}_FONT_H');
    hb.writeln();
    hb.writeln('#include <stdint.h>');
    hb.writeln();
    hb.writeln('typedef struct {');
    hb.writeln('  uint32_t codepoint;');
    hb.writeln('  uint8_t width;');
    hb.writeln('  uint8_t height;');
    hb.writeln('  uint8_t advance;');
    hb.writeln('  int8_t offsetX;');
    hb.writeln('  int8_t offsetY;');
    hb.writeln('  uint32_t dataOffset;');
    hb.writeln('  uint16_t dataSize;');
    hb.writeln('} font_glyph_t;');
    hb.writeln();
    hb.writeln('extern const font_glyph_t ${symbolName}_glyphs[];');
    hb.writeln('extern const uint32_t ${symbolName}_glyph_count;');
    hb.writeln();
    hb.writeln('#endif // ${symbolName.toUpperCase()}_FONT_H');
    hb.writeln();

    return (source: sb.toString(), header: hb.toString());
  }

  static void _writeByteArray(StringBuffer sb, List<int> bytes) {
    const perLine = 12;
    for (int i = 0; i < bytes.length; i += perLine) {
      final end = (i + perLine > bytes.length) ? bytes.length : i + perLine;
      final chunk = bytes
          .sublist(i, end)
          .map((b) => '0x${b.toRadixString(16).padLeft(2, '0')}')
          .join(', ');
      sb.writeln('  $chunk,');
    }
  }
}
