import 'dart:typed_data';

import 'dfnt_font.dart';

/// Parses a C array font file generated by `CArrayExporter` back into a
/// [DfntFont] so it can be rendered by the font test dialog.
///
/// Expected layout (see `CArrayExporter`):
/// - `// Cell: 8x16, BPP: 1, Scan: row, Glyphs: 95` header comment
/// - `static const uint8_t <name>_data[] = { 0x.., ... };`
/// - `const font_glyph_t <name>_glyphs[] = { { cp, w, h, adv, ox, oy, off, size }, ... };`
class CArrayFontParser {
  CArrayFontParser._();

  static final _cellRe =
      RegExp(r'//\s*Cell:\s*(\d+)x(\d+),\s*BPP:\s*(\d+)(?:,\s*Scan:\s*(\w+))?');
  static final _dataRe =
      RegExp(r'_data\[\]\s*=\s*\{(.*?)\};', dotAll: true);
  static final _byteRe = RegExp(r'0x([0-9A-Fa-f]{1,2})\b|\b(\d+)\b');
  static final _tableRe =
      RegExp(r'_glyphs\[\]\s*=\s*\{(.*?)\};', dotAll: true);
  static final _entryRe = RegExp(
    r'\{\s*0x([0-9A-Fa-f]+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,'
    r'\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\}',
  );

  /// Parses C [source] text. Throws [FormatException] on invalid data.
  static DfntFont parse(String source) {
    final dataMatch = _dataRe.firstMatch(source);
    if (dataMatch == null) {
      throw const FormatException('找不到位图数据数组 (_data[])');
    }
    // Clean out any C comments before parsing byte values so numbers in
    // comments (e.g. "// U+1B170 (64x128, 1024B)") don't corrupt the byte array.
    final rawDataText = dataMatch
        .group(1)!
        .replaceAll(RegExp(r'//.*'), '')
        .replaceAll(RegExp(r'/\*.*?\*/', dotAll: true), '');

    final bytes = <int>[];
    for (final m in _byteRe.allMatches(rawDataText)) {
      bytes.add(
          m.group(1) != null ? int.parse(m.group(1)!, radix: 16) : int.parse(m.group(2)!));
    }

    final tableMatch = _tableRe.firstMatch(source);
    if (tableMatch == null) {
      throw const FormatException('找不到字形表 (_glyphs[])');
    }
    final glyphs = <int, DfntGlyph>{};
    for (final m in _entryRe.allMatches(tableMatch.group(1)!)) {
      final codePoint = int.parse(m.group(1)!, radix: 16);
      final offset = int.parse(m.group(7)!);
      final size = int.parse(m.group(8)!);
      if (offset + size > bytes.length) {
        throw FormatException(
            '字形 U+${codePoint.toRadixString(16)} 数据越界');
      }
      glyphs[codePoint] = DfntGlyph(
        codePoint: codePoint,
        width: int.parse(m.group(2)!),
        height: int.parse(m.group(3)!),
        advance: int.parse(m.group(4)!),
        offsetX: int.parse(m.group(5)!),
        offsetY: int.parse(m.group(6)!),
        data: Uint8List.fromList(bytes.sublist(offset, offset + size)),
      );
    }
    if (glyphs.isEmpty) {
      throw const FormatException('字形表为空');
    }

    // Cell/bpp/scan from the header comment; fall back to the largest
    // glyph dimensions and 1bpp row-major for files without it.
    final cell = _cellRe.firstMatch(source);
    final cellWidth = cell != null
        ? int.parse(cell.group(1)!)
        : glyphs.values.map((g) => g.width).reduce((a, b) => a > b ? a : b);
    final cellHeight = cell != null
        ? int.parse(cell.group(2)!)
        : glyphs.values.map((g) => g.height).reduce((a, b) => a > b ? a : b);
    final bitsPerPixel = cell != null ? int.parse(cell.group(3)!) : 1;
    final columnMajor = cell?.group(4)?.toLowerCase() == 'column';

    return DfntFont(
      cellWidth: cellWidth,
      cellHeight: cellHeight,
      bitsPerPixel: bitsPerPixel,
      columnMajor: columnMajor,
      glyphs: glyphs,
    );
  }
}
