import 'packed_glyph.dart';
import 'unicode_blocks.dart';

/// Generates a C source/header pair containing the extracted font data.
///
/// Layout:
/// - a flat `uint8_t` array with all packed bitmaps concatenated
/// - a glyph descriptor table indexing into that array
class CArrayExporter {
  CArrayExporter._();

  /// Renders [glyphs] as a `.c` source file and matching `.h` header.
  /// Returns `(source, header)`.
  static ({String source, String header}) export({
    required String symbolName,
    required String fontLabel,
    required int cellWidth,
    required int cellHeight,
    required int bitsPerPixel,
    bool columnMajor = false,
    required List<PackedGlyph> glyphs,
  }) {
    final sb = StringBuffer();
    sb.writeln('// Generated by DebugToolSet Font Extractor');
    sb.writeln('// Font: $fontLabel');
    sb.writeln('// Cell: ${cellWidth}x$cellHeight, BPP: $bitsPerPixel, '
        'Scan: ${columnMajor ? 'column' : 'row'}, Glyphs: ${glyphs.length}');
    sb.writeln();
    sb.writeln('#include "${symbolName}_font.h"');
    sb.writeln();
    sb.writeln('static const uint8_t ${symbolName}_data[] = {');

    final offsets = <int>[];
    int offset = 0;

    // For large glyphs (e.g. 64x128), put up to 64 bytes per line
    // to keep line count small and ensure instant opening in IDE / diff tools.
    final perLine = (cellWidth * cellHeight >= 1024)
        ? 64
        : (cellWidth * cellHeight >= 256 ? 32 : 16);

    for (int idx = 0; idx < glyphs.length; idx++) {
      final g = glyphs[idx];
      offsets.add(offset);
      offset += g.data.length;

      final hexCp = formatCodePoint(g.codePoint);
      sb.writeln('  // $hexCp (${g.width}x${g.height}, ${g.data.length}B)');

      for (int i = 0; i < g.data.length; i += perLine) {
        final end = (i + perLine > g.data.length) ? g.data.length : i + perLine;
        final chunk = g.data
            .sublist(i, end)
            .map((b) => '0x${b.toRadixString(16).padLeft(2, '0')}')
            .join(', ');
        sb.writeln('  $chunk,');
      }
    }

    sb.writeln('};');
    sb.writeln();

    sb.writeln('const font_glyph_t ${symbolName}_glyphs[] = {');
    for (int i = 0; i < glyphs.length; i++) {
      final g = glyphs[i];
      final cpHex = formatCodePoint(g.codePoint, includePrefix: false);
      sb.writeln(
        '  { 0x$cpHex, '
        '${g.width}, ${g.height}, ${g.advance}, ${g.offsetX}, ${g.offsetY}, '
        '${offsets[i]}, ${g.data.length} },',
      );
    }
    sb.writeln('};');
    sb.writeln();
    sb.writeln('const uint32_t ${symbolName}_glyph_count = ${glyphs.length};');
    sb.writeln();

    final hb = StringBuffer();
    hb.writeln('// Generated by DebugToolSet Font Extractor');
    hb.writeln('// Font: $fontLabel');
    hb.writeln('#ifndef ${symbolName.toUpperCase()}_FONT_H');
    hb.writeln('#define ${symbolName.toUpperCase()}_FONT_H');
    hb.writeln();
    hb.writeln('#include <stdint.h>');
    hb.writeln();
    hb.writeln('typedef struct {');
    hb.writeln('  uint32_t codepoint;');
    hb.writeln('  uint8_t width;');
    hb.writeln('  uint8_t height;');
    hb.writeln('  uint8_t advance;');
    hb.writeln('  int8_t offsetX;');
    hb.writeln('  int8_t offsetY;');
    hb.writeln('  uint32_t dataOffset;');
    hb.writeln('  uint16_t dataSize;');
    hb.writeln('} font_glyph_t;');
    hb.writeln();
    hb.writeln('extern const font_glyph_t ${symbolName}_glyphs[];');
    hb.writeln('extern const uint32_t ${symbolName}_glyph_count;');
    hb.writeln();
    hb.writeln('#endif // ${symbolName.toUpperCase()}_FONT_H');
    hb.writeln();

    return (source: sb.toString(), header: hb.toString());
  }
}
